name: CI

on:
  push:
    branches: [master]
    paths:
      - grammar.js
      - src/**
      - test/**
      - bindings/**
      - binding.gyp
  pull_request:
    paths:
      - grammar.js
      - src/**
      - test/**
      - bindings/**
      - binding.gyp

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  test-parser:
    name: Test the parser
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-14]
    steps:
      - name: Set up repository
        uses: tree-sitter-grammars/actions/setup@main
        with:
          node-version: ${{vars.NODE_VERSION}}
      - name: Run tests
        uses: tree-sitter-grammars/actions/test@main
  test-package:
    name: Test the Python package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{vars.PYTHON_VERSION}}
      - name: Install dependencies
        run: pip install .
      - name: Run tests
        run: test/test_package.py
